frases = ['A dúvida já é a resposta',
          'Deixe pra trás o que não te leva pra frente',
          'Se for pra desistir, desista de ser fraco',
          'Aqui se faz, aqui se paga',
          'Sem sacrifício, não há vitória',
          'Você é o que escolhe ser',
          'Gel de cabelo é muito gorduroso',
          'O Feitiço das Gêmeas',
          'Popularidade é desejada por todos',
          'Eu sou alérgico a abelhas e amendoins',
          'Meu presente preferido é chocolate',
          'Apenas para sua informação',
          'O meu navegador favorito',
          'Esta é uma ideia muito boa']